# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cbb7a8d7daa04d9a891fd3d168b6d32ad5c18bd972c8e8b8acebb3aeac2f60fa245ab3d5cba3ef2430869f8dca8a54cb74992125e845c1b4549fe3efd31a93dc

test:
  secret_key_base: 73f6ddf396daf2749f9db13d78ef2d1e903d5ee78862a29288f2ff55d3925f7e0ace5b8626620548b1b6388e265d1db0b65445f4c1b5ca962d89c39911456046

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
